### ISSUE TITLE
When using @Story and @After errors are only printed at end of @After completion

### ISSUE THREAD

**Issue by Felteh** [alessandrosimi/guice-behave#1]
Hope all is well! Spotted our first issue on this project literally ever!

If you have a test which throws an exception - and then an @After after the test runs, any exception from the test is only printed AFTER the @After block executes. This is extremely confusing - particularly if @After throws an exception itself then it can be very hard to spot that your test threw exception since developers are accustomed to seeing lists of Exceptions as simply being a call chain of X threw exception, someone caught X higher up the stacktrace and re-threw in a different way, someone else caught this child of X and re-threw again - and not multiple uniquely separated exceptions.

Example Code:
``
@RunWith(StoryRunner.class)
@Modules(EmptyModule.class)
public class SanityTest {

```
@After
public void throwException() throws Exception {
    System.out.println("I should definitely be written to logs AFTER the test exception was");
    throw new Exception("after");
}

@Story
public void throwsException() throws Exception {
    throw new Exception("test");
}
```

}

class EmptyModule extends AbstractModule {
    @Override
    protected void configure() {

```
}
```

}
``

Logging returns:
I should definitely be written to logs AFTER the test exception was

java.lang.Exception: test
...stacktrace
java.lang.Exception: after
...stacktrace

**Comment by alessandrosimi** [comment]
Hi @Felteh, thanks for reporting the first issue of this project!
The reason you see this logging order is because JUnit stores all the exceptions and when the test is finished prints all of them.
I ensure you the execution order is correct.
If you are curious to know more about it you can look the `TestRunner` class that overrides the JUnit runner `BlockJUnit4ClassRunner`.

``` java
protected final void runChild(FrameworkMethod method, RunNotifier notifier) {
  EachTestNotifier eachNotifier = makeNotifier(method, notifier);
  ...
  try {
    // Run
    methodBlock(method).evaluate();
  } catch(AssumptionViolatedException e) {
    // Assumption Error
    eachNotifier.addFailedAssumption(e);
  } catch(Throwable e) {
    // Error
    eachNotifier.addFailure(e);
  } finally {
    // Finish
    eachNotifier.fireTestFinished();
  }
  ...
}
```

This method is basically a copy of the JUnit implementation. You can see the test is executed into a **try-catch** block and every exceptions are stored into the notifier.

Have you tried to use the `TestInterceptor` instead of `@After`? [This is the link of the documentation](https://github.com/alessandrosimi/guice-behave/wiki/Test-Runner#test-interceptor)

Again thanks,

Alessandro

**Comment by Felteh** [comment]
To my knowledge TestInterceptors have to be registered in the Module. This means that they are essentially 'application wide' (since we use only a single module for testing throughout the application).

This makes them quite far detached from the test itself - and would make the code less comprehensible and more difficult to follow what it was doing.

Unfortunately because the runChild method is marked as 'final' and 'makeNotifier' private I am unable to provide by own implementation of EachTestNotifier to modify the behaviour of this standard JUnit feature.

**Comment by alessandrosimi** [comment]
One module for the entire suite of tests is a good practice. It also has better performance because the Guice context is built only one once, so well done!

To solve your problem you can still use the test interceptor and a custom annotation.

``` java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER})
public @interface CleanDatabaseAfter{}
```

... and implement the interceptor in this way ...

``` java
public class CleanDatabaseInterceptor extends TestInterceptor {
    @Override
    public void afterTestRuns(Method method) {
        if (method.isAnnotationPresent(CleanDatabaseAfter.class)) {
            // Clean database
        }
    }
}
```

This is a nice approach because it avoids duplication of the **after** method and the annotation provides a very descriptive way to add behaviors to the tests.
You can even create many interceptor for many actions you want to do before or after the tests.
N.B. The the interceptors binding order is the order the interceptors are executed.
I hope this would help.

**Comment by Felteh** [comment]
(Its Dan from OCD so i've learnt from the best about good performance [You!], I forgot Github isn't showing my actual name hehe).

I guess I am poorly explaining - but my after method has no case for re-use. It is explicitly linked to the tests within that class. I have a couple of options - call it explicitly in my test (That's an ok approach I guess, but it actually has nothing to do with the assertions I am trying to achieve and confuses the issue). Or to put it elsewhere (In a Interceptor) and to only put a marker on the test (@SomeBehaviourIsHappeningElswhereGoodluckFindingIt) doesn't really aid the developer.

The @After annotation is perfect for read-ability - it separates test specific startup/shutdown requirements from clouding the business behaviour under test, and the execution order is explicitly specified [An interceptor can be both before and after - and you just 'hope' by naming convention its obvious when that interceptor is happening].

In a perfect world we'd like to remain using @After where appropriate but be able to print the error messages in the same order they happen so that developers have an easy life understanding when they happened. I get this is the limitation of the JUnit EachNotifier and not your library - but the library currently makes it unnecessarily hard to overcome the limitation so thought it was a good candidate for allowing extensibility in making the 'makeNotifier' method available for overriding.

**Comment by alessandrosimi** [comment]
Hey! Good to hear you. What you said is correct and the idea behind GuiceBehave was exactly this one: a support for Guice of JUnit test but be able to use all the functionality of JUnit.
What you asking it is possible but attaching to the `RunNotifier` a `RunListener`.Try to extend the runner and override the method `run` so you can attach listener to the notifier. Lister that print the stack trace when an exception happens.
